apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: murali
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 500Mi
