apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: murali
spec:
  containers:
  - name: my-container
    image: nginx
    resources:
      requests:
        memory: "3Gi"
        cpu: "1"
