apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret
type: Opaque
data:
  username: bXl1c2Vy      # base64-encoded "myuser"
  password: bXlwYXNzd29yZA==  # base64-encoded "mypassword"



apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: nginx:latest
        env:
        - name: MY_APP_USERNAME
          valueFrom:
            secretKeyRef:
              name: myapp-secret
              key: username
        - name: MY_APP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: myapp-secret
              key: password
